name: ZAP Scan

on:
  push:
    branches:
      - main

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debugging - List root directory contents
        run: |
          pwd
          ls -la

      - name: Setup ZAP
        run: |
          # Add commands to setup ZAP, e.g., downloading ZAP, starting it, etc.

      - name: Run ZAP scan
        run: |
          # Add commands to run ZAP scan

      - name: Check for .zap/rules.tsv file and output its content if it exists
        run: |
          if [ -f .zap/rules.tsv ]; then
            cat .zap/rules.tsv
          else
            echo ".zap/rules.tsv file not found"
          fi

